spring.datasource.url=${JGMOLI_DB_URL:jdbc:postgresql://localhost:5432/jgmoli_db}
spring.datasource.username=${JGMOLI_DB_USERNAME:${user.name}}
spring.datasource.password=${JGMOLI_DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
jgmoli.payment.demo-enabled=${JGMOLI_DEMO_PAYMENT_ENABLED:true}
